/* eslint-disable @typescript-eslint/indent */
export const PATTERNS = [
    {
        'id': 0,
        'name': 'Warm blue jumper',
        'image': 'https://www.knitted-patterns.com/images/stories/img/site_img/model_016/m_005.jpg',
        'description': 'Folly words widow one downs few age every seven. If miss part by fact he park just shew. Discovered had get considered projection who favourable. Necessary up knowledge it tolerably.',
        'category': 'Jumper',
        'complexity': 5,
    },
    {
        'id': 1,
        'name': 'A good winter hat',
        'image': 'https://i.pinimg.com/originals/73/c4/ec/73c4ec87f8c97b70868df13b50bf3ea3.jpg',
        'description': 'Another journey chamber way yet females man. Way extensive and dejection get delivered deficient sincerity gentleman age.',
        'category': 'Hat',
        'complexity': 1,
    },
    {
        'id': 2,
        'name': 'Another great blue jumper',
        'image': 'https://i.pinimg.com/736x/ca/3b/6e/ca3b6ef71a14527451b4ed8fac4fb222--mens-jumpers-benefits-of.jpg',
        'description': 'Sir joy northward sportsmen education. Discovery incommode earnestly no he commanded if it was possible to retard get me. Put still any about manor heard. ',
        'category': 'Jumper',
        'complexity': 3,
    },
    {
        'id': 3,
        'name': 'Crazy scarf',
        'image': 'https://knitted-patterns.com/images/stories/img/site_img/model_021/m_003-1.jpg',
        'description': 'Folly words widow one downs few age every seven. If miss part by fact he park just shew. Discovered had get considered projection who favourable. Necessary up knowledge it tolerably.',
        'category': 'Scarf',
        'complexity': 2,
    },
    {
        'id': 4,
        'name': 'Amazing pull-over',
        'image': 'https://www.theknittingnetwork.co.uk/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/M/e/Mens_Textured_Jumper_Knitting_Pattern_189e740f-9828-4455-a1f5-8605b0a74e98.jpg',
        'description': 'Another journey chamber way yet females man. Way extensive and dejection get delivered deficient sincerity gentleman age.',
        'category': 'Pull-over',
        'complexity': 4,
    },
    {
        'id': 5,
        'name': 'Colourful hat',
        'image': 'https://images.squarespace-cdn.com/content/v1/543bf675e4b08a84cfe5ef60/1574572094540-GT4QN0HK4RZRJVU1ICEK/ke17ZwdGBToddI8pDm48kE4CVXRkfnlWEFLoc2Xr1VFZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpzQXq7vwfUtCiVuprRsHrF7H2AvLLePT_YK8s8eiHEjtdpd9IEYrwaLEaA2guHxOaI/Plymouth+Mens+Hat.jpg',
        'description': 'Sir joy northward sportsmen education. Discovery incommode earnestly no he commanded if it was possible to retard get me. Put still any about manor heard. ',
        'category': 'Hat',
        'complexity': 3,
    },
    {
        'id': 6,
        'name': 'Warm blue jumper',
        'image': 'https://johnlewis.scene7.com/is/image/JohnLewis/238938519?$rsp-plp-port-320$',
        'description': 'Folly words widow one downs few age every seven. If miss part by fact he park just shew. Discovered had get considered projection who favourable. Necessary up knowledge it tolerably.',
        'category': 'Jumper',
        'complexity': 4,
    },
    {
        'id': 7,
        'name': 'A good winter hat',
        'image': 'https://i.pinimg.com/originals/73/c4/ec/73c4ec87f8c97b70868df13b50bf3ea3.jpg',
        'description': 'Another journey chamber way yet females man. Way extensive and dejection get delivered deficient sincerity gentleman age.',
        'category': 'Hat',
        'complexity': 1,
    },
    {
        'id': 8,
        'name': 'Another great blue jumper',
        'image': 'https://i.pinimg.com/736x/ca/3b/6e/ca3b6ef71a14527451b4ed8fac4fb222--mens-jumpers-benefits-of.jpg',
        'description': 'Sir joy northward sportsmen education. Discovery incommode earnestly no he commanded if it was possible to retard get me. Put still any about manor heard. ',
        'category': 'Jumper',
        'complexity': 3,
    },
]